PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS roles(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS users(
 id INTEGER PRIMARY KEY AUTOINCREMENT, full_name TEXT NOT NULL, student_id TEXT UNIQUE NOT NULL,
 email TEXT UNIQUE NOT NULL, phone TEXT NOT NULL, password_hash TEXT NOT NULL,
 role_id INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE IF NOT EXISTS canteens(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,location TEXT,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS menu_categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS menu_items(
 id INTEGER PRIMARY KEY AUTOINCREMENT,canteen_id INTEGER NOT NULL,category_id INTEGER NOT NULL,
 name TEXT NOT NULL,description TEXT,price REAL NOT NULL CHECK(price>0),image TEXT,
 availability INTEGER DEFAULT 1,stock_quantity INTEGER NOT NULL CHECK(stock_quantity>=0),
 preparation_time INTEGER DEFAULT 5,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(canteen_id) REFERENCES canteens(id),FOREIGN KEY(category_id) REFERENCES menu_categories(id));
CREATE TABLE IF NOT EXISTS orders(
 id INTEGER PRIMARY KEY AUTOINCREMENT,public_order_id TEXT UNIQUE NOT NULL,user_id INTEGER NOT NULL,canteen_id INTEGER NOT NULL,
 token_number INTEGER NOT NULL,total REAL NOT NULL CHECK(total>=0),status TEXT NOT NULL,
 pickup_slot TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(canteen_id) REFERENCES canteens(id),
 CHECK(status IN ('ORDER_PLACED','ACCEPTED','PREPARING','READY','COLLECTED','CANCELLED')));
CREATE TABLE IF NOT EXISTS order_items(
 id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,menu_item_id INTEGER NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),
 unit_price REAL NOT NULL CHECK(unit_price>0),FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(menu_item_id) REFERENCES menu_items(id));
CREATE TABLE IF NOT EXISTS queue(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER UNIQUE NOT NULL,position INTEGER NOT NULL,status TEXT NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id));
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,is_read INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,action TEXT NOT NULL,entity TEXT,entity_id INTEGER,timestamp TEXT DEFAULT CURRENT_TIMESTAMP,description TEXT,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_student ON users(student_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);
